name: rag-chatbot

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ""                 # force OpenAI off
      OLLAMA_BASE_URL: http://ollama:11434
      GENERATIVE_MODEL: llama3.1:8b
      LLM_MODEL: llama3.1:8b
      EMBEDDING_MODEL: nomic-embed-text
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    volumes:
      - ./data/db:/app/data/db
      - ./data/docs:/app/data/docs
    depends_on:
      - ollama
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    env_file:
      - .env
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  ollama: {}
