
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    env_file: .env
    depends_on:
      - api
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
